# Generated by Django 6.0.2 on 2026-03-20 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_medicalrecord_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointment_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('status_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('status_name', models.CharField(db_collation='Thai_CI_AS', max_length=50)),
                ('description', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Appointment_Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('bill_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Bills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('record_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, db_collation='Thai_CI_AS', null=True)),
                ('diagnosis', models.TextField(blank=True, db_collation='Thai_CI_AS', null=True)),
                ('treatment', models.TextField(blank=True, db_collation='Thai_CI_AS', null=True)),
            ],
            options={
                'db_table': 'Medical_Records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('medicine_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(db_collation='Thai_CI_AS', max_length=100)),
                ('type', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Medicines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('stock_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Medicine_Stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('owner_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_collation='Thai_CI_AS', max_length=50)),
                ('last_name', models.CharField(db_collation='Thai_CI_AS', max_length=50)),
                ('phone', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=15, null=True)),
                ('email', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Owners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('method_name', models.CharField(db_collation='Thai_CI_AS', max_length=50)),
                ('description', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Payment_Method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetAllergies',
            fields=[
                ('allergy_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('allergy_detail', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=255, null=True)),
                ('note', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Pet_Allergies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('pet_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('pet_name', models.CharField(db_collation='Thai_CI_AS', max_length=50)),
                ('breed', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Pets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(db_collation='Thai_CI_AS', max_length=100)),
                ('position', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(db_collation='Thai_CI_AS', max_length=100)),
                ('contact_name', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=15, null=True)),
                ('address', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('treatment_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('instruction', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Treatments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('username', models.CharField(db_collation='Thai_CI_AS', max_length=50)),
                ('password', models.CharField(db_collation='Thai_CI_AS', max_length=255)),
                ('role', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccinations',
            fields=[
                ('vaccination_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=100, null=True)),
                ('vaccination_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Vaccinations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinarians',
            fields=[
                ('vet_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('vet_name', models.CharField(db_collation='Thai_CI_AS', max_length=100)),
                ('specialization', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Veterinarians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineStockTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_id', models.CharField(max_length=6)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('quantity_change', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Medicine_Stock_Transaction',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='veterinarian',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='veterinarian',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='species',
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Veterinarian',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
