# Generated by Django 6.0.2 on 2026-03-20 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_appointments_appointmentstatus_bills_medicalrecords_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='species',
            table='Species',
        ),
    ]
