# Generated by Django 6.0.2 on 2026-03-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_add_stock_transaction_table'),
    ]

    operations = [
    ]
