# Generated by Django 6.0.2 on 2026-03-21 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_add_stock_transaction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestocktransaction',
            name='medicine_id',
            field=models.CharField(db_collation='Thai_CI_AS', max_length=6),
        ),
        migrations.CreateModel(
            name='POSTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(db_collation='Thai_CI_AS', max_length=6)),
                ('medicine_id', models.CharField(db_collation='Thai_CI_AS', max_length=6)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'POS_Transaction',
                'managed': True,
            },
        ),
    ]
