# Generated by Django 6.0.2 on 2026-03-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_medicinestocktransaction_medicine_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSBills',
            fields=[
                ('bill_id', models.CharField(db_collation='Thai_CI_AS', max_length=6, primary_key=True, serialize=False)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('pre_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'POS_Bills',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='postransaction',
            name='bill_id',
            field=models.CharField(blank=True, db_collation='Thai_CI_AS', max_length=6, null=True),
        ),
    ]
